name: "Chatbot 1"
description: "This is a chatbot that can answer questions and help with tasks"
system_prompt: "You are a helpful assistant that provides clear and concise answers."
llm:
  provider: "gemini"
  model: "gemini-2.0-flash"
  temperature: 0.7
  max_tokens: 1024
  api_key: "AIzaSyDLxORDHongevGVoSVXAwN6Xuhj13ef1bc"
memory:
  provider_name: "in-memory"
  config: {}